services:
  - type: web
    name: mental-health-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false # You will set it manually from Render dashboard
